version: '3.1'

services:
  api-be:
    container_name: api-be
    image: esi-hw1-backend
    build:
      context: ./../esi-hw1-backend
    restart: always
    expose:
      - 8080
    networks:
      - esi-hw1
         
  tests:
    container_name: tests
    image: esi_hw1_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/src/app'
      - '/src/app/node_modules'
    restart: always
    expose:
      - 3001
    depends_on:
      - api-be
    command: ["npm", "test"]
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - esi-hw1


networks:
  esi-hw1:
    driver: bridge
