version: '3.1'

services:
  api:
    container_name: api-be
    image: esi-hw1-backend
    build:
      context: ../../esi-hw1-backend
    restart: always
    command: [ "run", ".", "-dev" ]

  client:
    container_name: client
    build:
      context: ../../todo-client
    environment:
      - CHOKIDAR_USEPOLLING=true

  proxy:
    container_name: proxy
    build:
      context: ../../esi-hw1-service-config
    restart: always

  # the proxy won't start if mystery is not available
  mystery:
    container_name: mystery
    restart: always
    image: swaggerapi/swagger-ui
    expose:
      - 8080

  # TODO: From Martin: we should build our own image and get rid of the volume
  # TODO: Based from https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: "cypress/included:3.2.0"
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://proxy:8080
    # share the current folder as volume to avoid copying
    working_dir: /e2e
#    entrypoint: ["tail", "-f", "/dev/null"]
#    command: ["cypress", "run"]
    volumes:
      - ./:/e2e
